services:
  - type: web
    name: vite-react-app
    env: node
    region: oregon  # or any preferred region
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: NODE_ENV
        value: production
    rootDir: .  # Adjust if your project is in a subdirectory
