backend:
  name: git
  repo: velcrowaf/WanderlustAfrica
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

site_url: "https://wanderlustafrica.netlify.app/" # Replace with your site URL
base_path: "/admin" # Ensure this matches your admin path

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }